on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  push-to-prod:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: " 🚧 🚧 🚧A MERGE PROD 🚧 🚧 🚧"
    steps:
    - name: Hello world action step
      id: hello
      uses: tgrall-octodemo/simple-tug-action@main
      with:
        who-to-greet: 'PROD'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }} -- branch is ${GITHUB_REF#refs/heads/} }  --  "